version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"  # Different port to avoid conflicts with PM system
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      - chroma
    # NOTE: No database dependency - connects to external database via DATABASE_URL

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8001:8000"  # Different port to avoid conflicts
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    volumes:
      - chroma_data:/chroma/chroma

volumes:
  chroma_data:
    driver: local