services:
  backend:
    build: ./backend
    ports:
      - "8003:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/topsdraw_db
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000  # This is the internal port
    depends_on:
      db:
        condition: service_healthy
      chroma:
        condition: service_started
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=topsdraw_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8004:8000"  # Changed external port to 8004
    volumes:
      - chroma_data:/chroma/chroma

volumes:
  postgres_data:
  chroma_data: